[book]
authors = ["Luos"]
language = "en"
multilingual = false
src = "src"
title = "Luos.io - Documentation"
description = "Luos official documentation pages"

[output.html]
theme = "src/theme"
additional-css = ["src/_assets/css/custom.css"]
google-analytics = "UA-153509818-3"

[output.html.fold]
enable = true

[output.markdown]

[output.linkcheck]

[preprocessor.variables.variables]
node_def = "Hardware element (MCU) hosting and running Luos and hosting one or several containers."
container_def = "Software element run by Luos that can communicate with other containers. It can be a driver or an app. (Initially called a module)"
od_def = "Set of objects based on SI metric system that can be transmitted through Luos messages. Any object can easily be converted in other units."
microservices_def = "Microservices are a software development technique that arranges an application as a collection of loosely coupled services."
robus_def = "Bus communication protocol used by Luos."
luoshal_def = "Hardware Abstraction Layer used to fit Luos with various hardware designs."
last_version_pyluos = "1.5.0"
last_version_luos = "1.3.0"
gh_path = "github.com/Luos-io/doc/tree/master/src"

[preprocessor.links]
renderers = ["html"]
some_extra_feature = true

[preprocessor.index]
